df<-read.table("longread.pos.err")
df2<-read.table("shortread.pos.err3")
df3<-read.table("sample.err")
pdf("err_rate_as_pos3.pdf")
plot(df$V3,df$V1, axes=F, ylim=c(0,0.01),pch=16,col="purple2",xlim=c(0,600), xlab="Position in read", ylab="Error rate", main="Error rate distribution as read positions")
axis(1, cex=.9)
axis(2, las=1, cex=.9)
#box()
points(df2$V3,df2$V1,pch=17,col="maroon2")
points(df3$V3,df3$V1,pch=4, col="gold")
#library(gtools)
#err<-running(df2$V1,width=4,by=4)
#pos<-seq(1,77,by=4)
#points(pos, err, pch=18, col="black")
legend(450,0.009,c("CS reads", "short reads", "Sanger reads"), pch=c(16,17,4),col=c("purple2", "maroon2", "gold"))
dev.off()