cdsdel <- read.table("longread.del.stat")
nondel <- read.table("longread.del.noncoding.stat")
cdsins <- read.table("longread.ins.stat")
nonins <- read.table("longread.ins.noncoding.stat")

pdf("indel_longread_distribution.pdf", width=9, height=9)
#par(mfrow=c(1,2))
cdsdel25 <- sum(cdsdel$V1[cdsdel$V2>25])
nondel25 <- sum(nondel$V1[nondel$V2>25])
cdsins25 <- sum(cdsins$V1[cdsins$V2>25])
nonins25 <- sum(nonins$V1[nonins$V2>25])
cp <- barplot(c(cdsdel$V1[cdsdel$V2<=25],cdsdel25)+c(cdsins$V1[cdsins$V2<=25],cdsins25),axes=F,axisnames=F, xlab="Indel size in CDS", ylab="Frequency", main="Indel distribution in coding region", col="coral")
text(cp, par("usr")[3], labels=c(cdsdel$V2[cdsdel$V2<=25],">25"), cex=.8, xpd=T)
axis(2, las=1)
#np <- barplot(c(nondel$V1[nondel$V2<=25],nondel25)+c(nonins$V1[nonins$V2<=25],nonins25),axes=F,axisnames=F, names.arg=c(nondel$V2[nondel$V2<=25],">25"), xlab="Indel size", ylab="Frequency", main="Indel distribution in noncoding region", col="purple2")
#text(np, par("usr")[3], labels=c(nondel$V2[nondel$V2<=25],">25"), cex=.6, xpd=T)
#axis(2, las=1, cex=.9)
#barplot(c(cdsins$V1[cdsins$V2<=25],cdsins25), names.arg=c(cdsins$V2[cdsins$V2<=25],">25"), xlab="Insertion size", ylab="Frequency", main="Insertion distribution in coding region", col=colors()[505])
#barplot(c(nonins$V1[nonins$V2<=25],nonins25), names.arg=c(nonins$V2[nonins$V2<=25],">25"), xlab="Insertion size", ylab="Frequency", main="Insertion distribution in noncoding region", col=colors()[505])

dev.off()
